[build]
  command = "NODE_ENV=development npm install --no-workspaces --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[build.environment]
  NODE_ENV = "development"
